### PR TITLE
enables click on contents table moves to content

### PR DESCRIPTION
**Pull request by sapioit**
Welp, I had to make a different Pull Request...

### CODE REVIEW

**Comment by sapioit** [comment]
#5 @IonicaBizau

**Comment by IonicaBizau** [comment]
Is that required for all the sections? GitHub already adds anchors for the headings, so, I think we should take care only about the custom ones. 🎈

**Comment by sapioit** [comment]
if they're added, they definetly don't work... either way, I added `a name` for every language...

**Comment by IonicaBizau** [comment]
@sapioit What browser are you using? I'm merging this for now, but I'd be curious to reproduce it on my side too.

Thanks! 🍰

**Comment by IonicaBizau** [comment]
@sapioit Can you take a look at #10? 😀

**Comment by sapioit** [comment]
I'm using [Maxthon](http://maxthon.com) *[v4.4.8.2000](http://dl.maxthon.com/mx4/maxthon_portable_4.4.8.2000.7z)* (they already use [Explicit Versioning](https://medium.com/sapioit/92fc1f6bc73c) ^^)

**Pull request merged**
