### PR TITLE
enables click on contents table moves to content

### PR DESCRIPTION
**Pull request by sapioit**

### CODE REVIEW

**Comment by IonicaBizau** [comment]
@sapioit Thanks for this, but this should be fixed in the `package.json` file. The `README.md` file is generated from `package.json`.

**Comment by IonicaBizau** [comment]
I'm going to merge this, but if you can change it in the `package.json` file too, that would be great!

**Comment by IonicaBizau** [comment]
I have just fixed this. Interesting trick. 😂

**Comment by sapioit** [comment]
That explains why the file was already fixed, when I checked it. Thanks! ^^

**Comment by sapioit** [comment]
It's not working. You need to replace `'` with `\"`, because the HTML (on the majority of the browsers) doesen't accepts `\`` or `'` instead of `"`, for the tags. Some browsers do, but the most don't.

**Comment by sapioit** [comment]
I'm working on it.

**Comment by IonicaBizau** [comment]
Thanks, I didn't know that. It was working in my browser but improvements are always welcome. 😀

**Pull request merged**
